// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zcvnifvjuauwukvqvzsg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpjdm5pZnZqdWF1d3VrdnF2enNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4ODE1NDIsImV4cCI6MjA2MjQ1NzU0Mn0.8R-UH4F8doDVUNQTX34j-MdfJWeolf9sLSJRByvVqOI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);